import json
from src.llm import run_llm
from src.mcp_clients import sales

# TODO: fetch the below from sales mcp server /schema URL
DIMENSIONS = ["sales_person", "country", "product", "date"]
METRICS = ["total_sales", "boxes_shipped", "avg_sale"]
PAYLOAD_SKELETON = {
  "metrics": [],
  "dimensions": [],
  "filters": {},
  "time_range": {
    "start": "",
    "end": ""
  }
}

generated_payload_format = {
  "metrics": ["avg_sale"],
  "dimensions": [],
  "filters": {"product": "Widget", "country": "UK"},
  "time_range": {"start": "2023-01-01", "end": "2023-01-05"}
}

class SalesAgent:
    async def execute(self, query: str):
        """
        Converts a natural language query into
        a structured Sales MCP payload dynamically.
        """

        system = f"""
You are a Sales MCP Payload Planner. You MUST output a valid JSON object.

Your task:
1. Read the USER QUERY.
2. Fill the PAYLOAD SKELETON values based on the query.
3. Keep the structure exactly as provided.

Allowed Values:
- metrics: {", ".join(METRICS)}
- dimensions: {", ".join(DIMENSIONS)}
- filters keys: country, product, sales_person

Extraction Rules:
- Map entities found in the query to the corresponding 'filters' keys (e.g., "Australia" -> "country": "Australia").
- Dates must be YYYY-MM-DD.
- If a value is missing, use an empty string "" or empty array [].

Example:
Query: "Show avg sale for product Widget in UK from 2023-01-01 to 2023-01-05"
Output:
{json.dumps(generated_payload_format, indent=2)}

Return ONLY the JSON object.
"""

        user_message = f"""
USER QUERY:
{query}

PAYLOAD SKELETON:
{json.dumps(PAYLOAD_SKELETON, indent=2)}

"""
        response = await run_llm(system=system, user=user_message)

        if not response.strip():
            raise RuntimeError("Empty payload generated by SalesAgent")

        payload = json.loads(response)

        return await sales.query(payload)
